### ISSUE TITLE
學生文憑別需可修改

### ISSUE THREAD

**Issue by YuerLee** [0verseas/0verVerification#5]
在學生確認報名後、審核前，需可選擇該學生可選之文憑別。
報名前或審核後，不得修改。

**Comment by YuerLee** [comment]
改成審核時同時送。
只有聯合分發才需要選。

**Comment by ast850328** [comment]
做完了 https://github.com/0verseas/0verVerification/commit/cfcdb336986ebd349987282248683eb02c9c187b ，可是聽說不用了。
